/* Copyright (c) 2010-Now Christof Ressi, Winfried Ritsch and others.
 * For information on usage and redistribution, and for a DISCLAIMER OF ALL
 * WARRANTIES, see the file, "LICENSE.txt," in this distribution.  */

/** \file
 * \brief AOO request and response types
 */

#pragma once

#include "aoo_config.h"
#include "aoo_defines.h"
#include "aoo_types.h"

AOO_PACK_BEGIN

/*-------------------------------------------------------------*/

/** \brief request types */
AOO_ENUM(AooRequestType)
{
    /** error response */
    kAooRequestError = 0,
    /** connect to server */
    kAooRequestConnect,
    /** login to server */
    kAooRequestLogin,
    /** disconnect from server */
    kAooRequestDisconnect,
    /** join group */
    kAooRequestGroupJoin,
    /** leave group */
    kAooRequestGroupLeave,
    /** update group */
    kAooRequestGroupUpdate,
    /** update user */
    kAooRequestUserUpdate,
    /** custom request */
    kAooRequestCustom
};

/*============================================================*/
/*                         request                            */
/*============================================================*/

/** \brief common header for all request structures */
#define AOO_REQUEST_HEADER          \
    /** \cond DO_NOT_DOCUMENT */    \
    AooRequestType type;            \
    AooUInt32 structSize;           \
    /** \endcond */

/** \brief basic request */
typedef struct AooRequestBase
{
    AOO_REQUEST_HEADER
} AooRequestBase;

/** \cond DO_NOT_DOCUMENT */
#define AOO_REQUEST_INIT(name, field) \
    kAooRequest##name, AOO_STRUCT_SIZE(AooRequest##name, field)
/** \endcond */

/*============================================================*/
/*                         response                           */
/*============================================================*/

/** \brief common header for all response structures */
#define AOO_RESPONSE_HEADER AOO_REQUEST_HEADER

/** \brief basic response */
typedef struct AooResponseBase
{
    AOO_RESPONSE_HEADER
} AooResponseBase;

/** \cond DO_NOT_DOCUMENT */
#ifdef __cplusplus
#define AOO_RESPONSE_BASE(name, field) \
    type(kAooRequest##name), \
    structSize(AOO_STRUCT_SIZE(AooResponse##name, field))
#endif

#define AOO_RESPONSE_INIT(name, field) \
    kAooRequest##name, AOO_STRUCT_SIZE(AooResponse##name, field)
/** \endcond */

/*============================================================*/
/*                           error                            */
/*============================================================*/

/** \brief error response
 *
 * \attention (C only) always initialize with AOO_RESPONSE_ERROR_INIT()!
 */
typedef struct AooResponseError
{
#ifdef __cplusplus
    /** default constructor */
    AooResponseError()
        : AOO_RESPONSE_BASE(Error, errorMessage),
          errorCode(0), errorMessage("") {}
#endif

    AOO_RESPONSE_HEADER
    /** platform- or user-specific error code */
    AooInt32 errorCode;
    /** discriptive error message */
    const AooChar *errorMessage;
} AooResponseError;

/** \brief (C only) default initializer for AooResponseError struct */
#define AOO_RESPONSE_ERROR_INIT() \
    { AOO_RESPONSE_INIT(Error, errorMessage), 0, "" }

/*============================================================*/
/*                   connect (client-side)                    */
/*============================================================*/

/** \brief connection request */
typedef struct AooRequestConnect
{
    AOO_REQUEST_HEADER
    /** the server endpoint address */
    AooIpEndpoint address;
    /** (optional) password */
    const AooChar *password;
    /** (optional) metadata */
    const AooData *metadata;
} AooRequestConnect;

/** \brief connection response */
typedef struct AooResponseConnect
{
    AOO_RESPONSE_HEADER
    /** the client ID generated by the server */
    AooId clientId;
    /** server version string */
    const AooChar *version;
    /** (optional) metadata returned by the server */
    const AooData *metadata;
} AooResponseConnect;

/*============================================================*/
/*                 disconnect (client-side)                   */
/*============================================================*/

/** \brief disconnect request */
typedef struct AooRequestDisconnect
{
    AOO_REQUEST_HEADER
} AooRequestDisconnect;


/** \brief disconnect response */
typedef struct AooResponseDisconnect
{
    AOO_RESPONSE_HEADER
} AooResponseDisconnect;


/*============================================================*/
/*                    login (server-side)                     */
/*============================================================*/

/** \brief login request */
typedef struct AooRequestLogin
{
    AOO_REQUEST_HEADER
    /** the client version string */
    const AooChar *version;
    /** (optional) the password (hashed) */
    const AooChar *password;
    /** (optional) client metadata */
    const AooData *metadata;
} AooRequestLogin;


/** \brief login response
 *
 * \attention (C only) always initialize with AOO_RESPONSE_LOGIN_INIT()!
 */
typedef struct AooResponseLogin
{
#ifdef __cplusplus
    /** default constructor */
    AooResponseLogin()
        : AOO_RESPONSE_BASE(Login, metadata),
          metadata(NULL) {}
#endif

    AOO_RESPONSE_HEADER
    /** (optional) metadata returned by the server */
    const AooData *metadata;
} AooResponseLogin;

/** \brief (C only) default initializer for AooResponseLogin struct */
#define AOO_RESPONSE_LOGIN_INIT() \
    { AOO_RESPONSE_INIT(Login, metadata), NULL }

/*============================================================*/
/*                 join group (server/client)                 */
/*============================================================*/

/** \brief request for joining a group */
typedef struct AooRequestGroupJoin
{
    AOO_REQUEST_HEADER
    /*------------------------ group ------------------------*/
    /** the group name */
    const AooChar *groupName;
    /** (optional) the group password */
    const AooChar *groupPwd;
    /** the group ID; #kAooIdNone if group does not exist (yet) */
    AooId groupId;
    /** (optional) group metadata
     * The client who creates the group may provide group metadata
     * in AooClient::joinGroup(). By default, the server just stores
     * the metadata and sends it to all subsequent users via this field.
     * However, it may also intercept the request and validate/modify the
     * metadata, or provide any kind of metadata it wants, by setting
     * AooResponseGroupJoin::groupMetadata. */
    const AooData *groupMetadata;
    /*------------------------ user ------------------------*/
    /** the user name */
    const AooChar *userName;
    /** the user password */
    const AooChar *userPwd;
    /** the user ID; #kAooIdNone if user does not exist (yet) */
    AooId userId;
    /** (optional) user metadata
     * Each client may provide user metadata in AooClient::joinGroup().
     * By default, the server just stores the metadata and sends it to all
     * peers via AooEventPeer::metadata. However, it may also intercept
     * the request and validate/modify the metadata, or provide any kind of
     * metadata it wants, by setting AooResponseGroupJoin::userMetadata. */
    const AooData *userMetadata;
    /*------------------------ other -----------------------*/
    /** (optional) UDP relay address provided by the user/client.
     * The server will forward it to all peers. */
    const AooIpEndpoint *relayAddress;
} AooRequestGroupJoin;


/** \brief response for joining a group
 *
 * \attention (C only) always initialize with AOO_RESPONSE_GROUP_JOIN_INIT()!
 */
typedef struct AooResponseGroupJoin
{
#ifdef __cplusplus
    /** default constructor */
    AooResponseGroupJoin()
        : AOO_RESPONSE_BASE(GroupJoin, relayAddress),
          groupId(kAooIdInvalid), groupFlags(kAooIdInvalid),
          groupMetadata(NULL), userId(kAooIdInvalid),
          userMetadata(NULL), privateMetadata(NULL),
          relayAddress(NULL) {}
#endif

    AOO_RESPONSE_HEADER
    /*------------------------ group --------------------------*/
    /** group ID generated by the server */
    AooId groupId;
    /** group flags */
    AooGroupFlags groupFlags;
    /** (optional) group metadata, validated/modified by the server. */
    const AooData *groupMetadata;
    /*------------------------ user ---------------------------*/
    /** user Id generated by the server */
    AooId userId;
    /** user flags */
    AooUserFlags userFlags;
    /** (optional) user metadata, validated/modified by the server. */
    const AooData *userMetadata;
    /*------------------------ other --------------------------*/
    /** (optional) private metadata that is only sent to the client.
     * For example, this can be used for state synchronization. */
    const AooData *privateMetadata;
    /** (optional) UDP relay address provided by the server.
     * For example, you may provide a group with a dedicated UDP
     * relay server.
     * If `hostName` is `NULL`, it means that the relay has the same
     * IP address(es) as the AOO server. */
    const AooIpEndpoint *relayAddress;
} AooResponseGroupJoin;

/** \brief (C only) default initializer for AooResponseGroupJoin struct */
#define AOO_RESPONSE_GROUP_JOIN_INIT() \
    { AOO_RESPONSE_INIT(GroupJoin, relayAddress), kAooIdInvalid, 0, NULL, \
        kAooIdInvalid, 0, NULL, NULL, NULL }

/*============================================================*/
/*                 leave group (server/client)                */
/*============================================================*/

/** \brief request for leaving a group */
typedef struct AooRequestGroupLeave
{
    AOO_REQUEST_HEADER
    /** the group ID */
    AooId group;
} AooRequestGroupLeave;


/** \brief response for leaving a group */
typedef struct AooResponseGroupLeave
{
#ifdef __cplusplus
    /** default constructor */
    AooResponseGroupLeave()
        : AOO_RESPONSE_BASE(GroupLeave, structSize) {}
#endif
    AOO_REQUEST_HEADER
} AooResponseGroupLeave;

/** \brief (C only) default initializer for AooResponseGroupLeave struct */
#define AOO_RESPONSE_GROUP_LEAVE_INIT() \
    { AOO_RESPONSE_INIT(GroupLeave, structSize) }

/*============================================================*/
/*                   update group metadata                    */
/*============================================================*/

/** \brief request for updating a group */
typedef struct AooRequestGroupUpdate
{
    AOO_REQUEST_HEADER
    /** the group ID */
    AooId groupId;
    /** the new group metadata */
    AooData groupMetadata;
} AooRequestGroupUpdate;


/** \brief response for updating a group
 *
 * \attention (C only) always initialize with AOO_RESPONSE_GROUP_UPDATE_INIT()!
 */
typedef struct AooResponseGroupUpdate
{
#ifdef __cplusplus
    /** default constructor */
    AooResponseGroupUpdate()
        : AOO_RESPONSE_BASE(GroupUpdate, groupMetadata),
          groupMetadata{ kAooDataUnspecified, NULL, 0 } {}
#endif

    AOO_RESPONSE_HEADER
    /** the actual new group metadata, possibly modified by the server */
    AooData groupMetadata;
} AooResponseGroupUpdate;

/** \brief (C only) default initializer for AooResponseGroupJoin struct */
#define AOO_RESPONSE_GROUP_UPDATE_INIT() \
    { AOO_RESPONSE_INIT(GroupUpdate, groupMetadata), \
        { kAooDataUnspecified, NULL, 0 } }

/*============================================================*/
/*                   update user metadata                     */
/*============================================================*/

/** \brief request for updating a user */
typedef struct AooRequestUserUpdate
{
    AOO_REQUEST_HEADER
    /** the group ID */
    AooId groupId;
    /** the user ID (server-side only) */
    AooId userId;
    /** the new user metadata */
    AooData userMetadata;
} AooRequestUserUpdate;


/** \brief response for updating a user
 *
 * \attention (C only) always initialize with AOO_RESPONSE_USER_UPDATE_INIT()!
 */
typedef struct AooResponseUserUpdate
{
#ifdef __cplusplus
    /** default constructor */
    AooResponseUserUpdate()
        : AOO_RESPONSE_BASE(UserUpdate, userMetadata),
          userMetadata{ kAooDataUnspecified, NULL, 0 } {}
#endif

    AOO_RESPONSE_HEADER
    /** the actual new user metadata, possibly modified by the server */
    AooData userMetadata;
} AooResponseUserUpdate;

/** \brief (C only) default initializer for AooResponseUserJoin struct */
#define AOO_RESPONSE_USER_UPDATE_INIT() \
    { AOO_RESPONSE_INIT(UserUpdate, userMetadata), \
        { kAooDataUnspecified, NULL, 0 } }

/*============================================================*/
/*                 custom request (server/client)             */
/*============================================================*/

/** \brief custom client request */
typedef struct AooRequestCustom
{
    AOO_REQUEST_HEADER
    /** application-specific request data */
    AooData data;
    /** flags (currently unused) */
    AooFlag flags;
} AooRequestCustom;


/** \brief custom server response
 *
 * \attention (C only) always initialize with AOO_RESPONSE_CUSTOM_INIT()!
 */
typedef struct AooResponseCustom
{
#ifdef __cplusplus
    /** default constructor */
    AooResponseCustom()
        : AOO_RESPONSE_BASE(Custom, flags),
          data{ kAooDataUnspecified, NULL, 0 }, flags(0) {}
#endif

    AOO_RESPONSE_HEADER
    /** application specific resposne data */
    AooData data;
    /** flags (currently unused) */
    AooFlag flags;
} AooResponseCustom;

/** \brief (C only) default initializer for AooResponseCustom struct */
#define AOO_RESPONSE_CUSTOM_INIT() \
    { AOO_RESPONSE_INIT(Custom, flags), { kAooDataUnspecified, NULL, 0 }, 0 }

/*-----------------------------------------------------------*/

/** \brief union of all client requests */
union AooRequest
{
    AooRequestType type; /**< \brief request type */
    AooRequestConnect connect; /**< \brief connect */
    AooRequestDisconnect disconnect; /**< \brief disconnect */
    AooRequestLogin login; /**< \brief login */
    AooRequestGroupJoin groupJoin; /**< \brief join group */
    AooRequestGroupLeave groupLeave; /**< \brief leave group */
    AooRequestGroupUpdate groupUpdate; /**< \brief update group */
    AooRequestUserUpdate userUpdate; /**< \brief update user */
    AooRequestCustom custom; /**< \brief custom */
};

/*----------------------------------------------------------*/

/** \brief union of all client responses */
union AooResponse
{
    AooRequestType type; /**< \brief request type */
    AooResponseError error; /**< \brief error */
    AooResponseConnect connect; /**< \brief connect */
    AooResponseDisconnect disconnect; /**< \brief disconnect */
    AooResponseLogin login; /**< \brief login */
    AooResponseGroupJoin groupJoin; /**< \brief join group */
    AooResponseGroupLeave groupLeave; /**< \brief leave group */
    AooResponseGroupUpdate groupUpdate; /**< \brief update group */
    AooResponseUserUpdate userUpdate; /**< \brief update user */
    AooResponseCustom custom; /**< \brief custom */
};

/*----------------------------------------------------------*/

AOO_PACK_END
